blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.home, name='home'),
    path('new_post/', views.new_post, name='new_post'),
    path('post_detals/<int:post_id>/', views.post_details, name='post_details'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),

]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']  # Изменяемые
        exclude = ['author']  # Игнорировать поле при создании формы, но автоматически устанавливаться в представлениях.

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import BlogPost
from .forms import BlogPostForm


def home(request):
    # Получаем список всех блог-постов, упорядоченных по дате добавления
    posts = BlogPost.objects.order_by('-date_added')
    return render(request, 'blogs/home.html', {'posts': posts})


def post_details(request, post_id):
    # Получаем конкретный блог-пост по его идентификатору
    post = BlogPost.objects.get(id=post_id)
    return render(request, 'blogs/post_details.html', {'post': post})


@login_required
def edit_post(request, post_id):
    # Получаем конкретный блог-пост по его идентификатору
    post = BlogPost.objects.get(id=post_id)
    if post.author != request.user:
        raise Http404
    if request.user == post.author:
        if request.method == 'POST':
            # Если данные отправлены методом POST, создаем форму на основе полученных данных
            form = BlogPostForm(request.POST, instance=post)
            if form.is_valid():
                form.instance.author = request.user  # Установите автора перед сохранением
                form.save()
                # updated_post = form.save()  # Сохраняем изменения и получаем обновленный пост
                return redirect('blogs:post_details', post_id=post.id)
        else:
            # Если данные не отправлены методом POST, показываем форму для редактирования
            form = BlogPostForm(instance=post)
        return render(request, 'blogs/edit_post.html', {'form': form, 'post': post})
    else:
        # Если текущий пользователь не является автором поста, перенаправляем на домашнюю страницу
        return redirect('home')


@login_required
def new_post(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(request.POST)
        if form.is_valid():
            blog_post = form.save(commit=False)
            blog_post.author = request.user  # Устанавливаем текущего пользователя как автора поста
            blog_post.save()
            # form.instance.author = request.user  # Установите автора перед сохранением
            # form.save()
            return redirect('blogs:home')
    return render(request, 'blogs/new_post.html', {'form': form})

@login_required
def my_posts(request):
    user_posts = BlogPost.objects.filter(author=request.user)
    return render(request, 'blogs/my_posts.html', {'user_posts': user_posts})


def delete_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)

    # Проверка, что текущий пользователь - автор поста
    if request.user == post.author:
        post.delete()

    return redirect('blogs:home')  # Перенаправление на домашнюю страницу после удаления поста

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('blogs:home')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta content="ie=edge">
    <title>Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blogs:home' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs:my_posts' %}">My posts</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text"> Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Exit</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>

<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Edit Post</h1>
{% endblock page_header %}

{% block content %}

    <form method="post"
          action="{% url 'blogs:edit_post' post.id %}"
          class="form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Save</button>
        {% endbuttons %}

        <a class="btn btn-secondary" href="{% url 'blogs:post_details' post.id %}">Save  иии</a>
    </form>

    <input type="hidden" name="next" value="{% url 'blogs:post_details' post.id %}"/>

{% endblock content %}

blogs/templates/blogs/home.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Posts</h1>
{% endblock page_header %}

{% block content %}
    {% for post in posts %}
        <div class="card" style="width: 100%;">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'blogs:post_details' post.id %}">
                        <h4>{{ post.title }}</h4>
                    </a>
                    <p>{{ post.text }}</p>
                    <p>Author: {{ post.author }}</p>
                    <p>Date: {{ post.date_added }}</p>
                </li>
            </ul>
        </div>
    {% empty %}
        <li><h4>No post</h4></li>
    {% endfor %}
    <br>
    <a class="btn btn-outline-info" href="{% url 'blogs:new_post' %}">New post</a>
{% endblock content %}

blogs/templates/blogs/my_posts.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>My Posts</h1>
{% endblock page_header %}

{% block content %}
    <div class="list-group">
        {% for post in user_posts %}
            <a href="{% url 'blogs:post_details' post.id %}" class="list-group-item list-group-item-action">
                <h4 class="list-group-item-heading">{{ post.title }}</h4>
                <p class="list-group-item-text">{{ post.text }}</p>
                <p class="list-group-item-text">Author: {{ post.author }}</p>
                <p class="list-group-item-text">Date Added: {{ post.date_added }}</p>
            </a>
        {% empty %}
            <p>No posts yet.</p>
        {% endfor %}
    </div>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Create New Post</h1>
{% endblock page_header %}

{% block content %}
    <form method="post"
          action="{% url 'blogs:new_post' %}"
          class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Create</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blogs/post_details.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Post Details</h1>
{% endblock page_header %}

{% block content %}
    <div class="card">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <h4>{{ post.title }}</h4>
                <p>{{ post.text }}</p>
                <p>Author: {{ post.author }}</p>
                <p>Date: {{ post.date_added }}</p>
                {% if user.is_authenticated %}
                    {% if user == post.author %}
                        <a class="btn btn-primary" href="{% url 'blogs:edit_post' post.id %}">Edit</a>
                        <a class="btn btn-danger" href="{% url 'blogs:delete_post' post.id %}">Delete</a>
                    {% endif %}
                {% endif %}
            </li>
        </ul>
    </div>
    <br>
    <a class="btn btn-outline-info" href="{% url 'blogs:home' %}">Back to Posts</a>
{% endblock content %}